spring:
  datasource:
    username: beer_order_service
    password: password
    url: jdbc:mysql://localhost:3306/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#logging:
#  level:
#    org.hibernate.sql: debug
#    com.zaxxer.hikari.HikariConfig: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
