spring:
  datasource:
    username: beer_inventory_service
    password: password
    url: jdbc:mysql://localhost:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
logging:
  level:
#    org.hibernate.sql: debug
#    com.zaxxer.hikari.HikariConfig: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
     io.ashisht: debug
